spring:
  cloud:
    gateway:
      routes:
        - id: business-service-routes
          uri: ${BUSINESS_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/**

BUSINESS_SERVICE_URL: http://localhost:8082
